/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AccountType = "EMAIL" | "PHONE";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type InvitationStatus = "accepted" | "expired" | "pending" | "revoked";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type SubscriptionEventType = "cancelled" | "downgraded" | "linked" | "payment_failed" | "payment_succeeded" | "trial_expired" | "trial_started" | "unlinked" | "upgraded";

export type SubscriptionPeriod = "monthly" | "yearly";

export type SubscriptionPlatform = "android" | "ios" | "web";

export type SubscriptionStatus = "active" | "cancelled" | "expired" | "free" | "payment_failed" | "trial";

export type ThemeCategory = "custom" | "preestablished";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type VerificationCodeStatus = "EXPIRED" | "PENDING" | "USED";

export type VerificationCodeType = "EMAIL_CONFIRMATION" | "PASSWORD_RESET" | "PHONE_CONFIRMATION";

export interface Accounts {
  access_token: string | null;
  created_at: Generated<Timestamp>;
  expires_at: number | null;
  id: Generated<string>;
  id_token: string | null;
  /**
   * Proveedor OAuth (google, facebook, etc.)
   */
  provider: string;
  /**
   * ID del usuario en el proveedor
   */
  provider_account_id: string;
  refresh_token: string | null;
  scope: string | null;
  session_state: string | null;
  token_type: string | null;
  type: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AsignacionesPresupuesto {
  billetera_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  moneda_id: string;
  monto: Numeric;
  sobre_id: string;
  tipo: string;
  usuario_id: string;
}

export interface Billeteras {
  color: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  emoji: string | null;
  id: Generated<string>;
  is_compartida: Generated<boolean>;
  moneda_principal_id: Generated<string>;
  nombre: string;
  saldo_proyectado: Generated<Numeric>;
  saldo_real: Generated<Numeric>;
  saldos_multimoneda: Json | null;
  tasa_interes: Generated<Numeric | null>;
  tipo: string;
  updated_at: Generated<Timestamp>;
  usuario_id: string;
}

export interface BilleterasTransacciones {
  billetera_destino_id: string | null;
  billetera_id: string;
  billetera_origen_id: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  descripcion: string | null;
  fecha: Generated<Timestamp>;
  id: Generated<string>;
  moneda_id: string;
  monto: Numeric;
  saldo_real_post: Numeric;
  tipo: string;
  usuario_id: string;
}

export interface Categorias {
  color: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  emoji: string | null;
  id: Generated<string>;
  nombre: string;
  updated_at: Generated<Timestamp>;
  usuario_id: string;
}

export interface IngresosRecurrentes {
  auto_distribuir: Generated<boolean>;
  billetera_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  dia: number;
  distribucion: Json | null;
  estado: Generated<string>;
  frecuencia: string;
  id: Generated<string>;
  moneda_id: string;
  monto: Numeric;
  nombre: string;
  proxima_ejecucion: Timestamp | null;
  updated_at: Generated<Timestamp>;
  usuario_id: string;
}

export interface InvalidatedSessions {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  /**
   * Timestamp de invalidación - tokens emitidos antes de esta fecha deben refrescarse
   */
  invalidated_at: Generated<Timestamp>;
  /**
   * Motivo de invalidación (para debugging)
   */
  reason: string | null;
  /**
   * Usuario cuya sesión fue invalidada
   */
  user_id: string;
}

export interface InvitacionesListas {
  /**
   * Código único para aceptar la invitación vía link
   */
  codigo_invitacion: string | null;
  created_at: Generated<Timestamp | null>;
  /**
   * Estado de la invitación: PENDIENTE, ACEPTADA, RECHAZADA, CANCELADA
   */
  estado: Generated<string>;
  expires_at: Timestamp | null;
  id: Generated<string>;
  invitado_email_o_telefono: string;
  invitado_por_id: string;
  invitado_user_id: string | null;
  lista_id: string;
  /**
   * Rol que tendrá el usuario: EDITOR (editar items) o EXECUTION_ONLY (solo comprar)
   */
  rol: Generated<string>;
  updated_at: Generated<Timestamp | null>;
}

export interface InvitacionesSobres {
  codigo_invitacion: string | null;
  created_at: Generated<Timestamp>;
  estado: Generated<string>;
  expires_at: Timestamp | null;
  id: Generated<string>;
  invitado_email_o_telefono: string | null;
  invitado_por_id: string;
  invitado_user_id: string | null;
  rol: Generated<string>;
  sobre_id: string;
  updated_at: Generated<Timestamp>;
}

export interface InvitationCodes {
  /**
   * Código único compartible (ej: ABC123XYZ)
   */
  code: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  /**
   * Cuántas veces puede usarse el código
   */
  max_uses: Generated<number>;
  owner_user_id: string;
  plan_id: string;
  status: Generated<InvitationStatus>;
  updated_at: Generated<Timestamp>;
  uses_count: Generated<number>;
}

export interface LinkedUsers {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  linked_at: Generated<Timestamp>;
  /**
   * Usuario que recibe acceso sin pagar
   */
  linked_user_id: string;
  /**
   * Usuario propietario que paga el plan
   */
  owner_user_id: string;
}

export interface Monedas {
  activa: Generated<boolean>;
  created_at: Generated<Timestamp>;
  decimales: Generated<number>;
  id: string;
  nombre: string;
  orden: Generated<number>;
  simbolo: string;
  tipo: string;
  updated_at: Generated<Timestamp>;
}

export interface Notificaciones {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  /**
   * Indica si el usuario ya leyó la notificación
   */
  leida: Generated<boolean | null>;
  mensaje: string;
  /**
   * Datos adicionales en formato JSON (sobre_id, sobre_historico_id, lista_id, etc.)
   */
  metadata: Json | null;
  /**
   * Tipo de notificación: PERDIDA_ACCESO_SOBRE, PERDIDA_ACCESO_LISTA, etc.
   */
  tipo: string;
  titulo: string;
  updated_at: Generated<Timestamp | null>;
  usuario_id: string;
}

export interface PaymentProducts {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  currency: string;
  id: Generated<string>;
  period: SubscriptionPeriod;
  plan_id: string;
  platform: SubscriptionPlatform;
  /**
   * ID del producto en Stripe/Apple/Google
   */
  platform_product_id: string;
  /**
   * Precio en la moneda especificada
   */
  price: Numeric;
  updated_at: Generated<Timestamp>;
}

export interface PendingPurchases {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  platform: string;
  product_id: string;
  /**
   * pending: esperando webhook, completed: procesado, failed: error
   */
  status: Generated<string>;
  /**
   * originalTransactionId (Apple) o purchaseToken (Google)
   */
  transaction_id: string;
  user_id: string;
}

export interface Periodos {
  activo: Generated<boolean>;
  created_at: Generated<Timestamp>;
  dia_inicio: number | null;
  fecha_fin: Timestamp;
  fecha_inicio: Timestamp;
  id: Generated<string>;
  tipo: string;
  user_id: string;
}

export interface PlanCapabilities {
  /**
   * Clave de la capacidad (ej: export_data, advanced_reports)
   */
  capability_key: string;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  plan_id: string;
}

export interface PlanLimits {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  /**
   * Cantidad máxima permitida (NULL = ilimitado)
   */
  max_quantity: number | null;
  plan_id: string;
  /**
   * Clave del recurso (ej: projects, storage_mb)
   */
  resource_key: string;
}

export interface PresupuestoAjustesLog {
  campo: string;
  categoria_id: string | null;
  /**
   * Positive values = increase, negative values = decrease
   */
  diferencia: Numeric | null;
  fecha_ajuste: Generated<Timestamp>;
  id: Generated<string>;
  motivo: string | null;
  periodo_month: number;
  periodo_year: number;
  sobre_id: string;
  tipo_ajuste: string;
  usuario_id: string;
  valor_anterior: Numeric | null;
  valor_nuevo: Numeric | null;
}

export interface ProductCatalog {
  /**
   * Referencia a product_categories_global (SIN FK para independencia)
   */
  category_id: string | null;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  descripcion: string | null;
  id: Generated<string>;
  /**
   * Idioma del producto (es, en, pt). Un producto en español sirve para todos los países hispanohablantes.
   */
  idioma: Generated<string>;
  nombre: string;
  updated_at: Generated<Timestamp | null>;
}

export interface ProductCategoriesGlobal {
  color: string | null;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  descripcion: string | null;
  emoji: string | null;
  id: Generated<string>;
  idioma: Generated<string>;
  nombre: string;
  updated_at: Generated<Timestamp | null>;
}

export interface ProductCategoriesUser {
  color: string | null;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  emoji: string | null;
  id: Generated<string>;
  nombre: string;
  updated_at: Generated<Timestamp | null>;
  user_id: string;
}

export interface ProductFavorites {
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  /**
   * DEPRECATED: Siempre false. Mantener solo para migración.
   */
  is_catalog: Generated<boolean>;
  product_custom_id: string | null;
  /**
   * DEPRECATED: No usar. Mantener solo para migración de datos legacy.
   */
  product_id: string | null;
  user_id: string;
}

export interface ProductFrequency {
  count_purchases: Generated<number>;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  is_catalog: Generated<boolean>;
  last_purchase_date: Timestamp | null;
  product_custom_id: string | null;
  product_id: string | null;
  updated_at: Generated<Timestamp | null>;
  user_id: string;
}

export interface ProductPricesHistory {
  currency_id: string | null;
  id: Generated<string>;
  is_catalog: Generated<boolean>;
  price: Numeric;
  product_custom_id: string | null;
  product_id: string | null;
  recorded_at: Generated<Timestamp | null>;
  store_name: string;
  user_id: string;
}

export interface ProductUserCustom {
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  descripcion: string | null;
  id: Generated<string>;
  nombre: string;
  updated_at: Generated<Timestamp | null>;
  user_id: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  /**
   * Fecha de expiración de la sesión
   */
  expires: Timestamp;
  id: Generated<string>;
  /**
   * Token único de sesión
   */
  session_token: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ShoppingExecutionItems {
  agregado_por: string | null;
  cantidad_comprada: Numeric | null;
  categoria_global_id: string | null;
  categoria_producto_id: string | null;
  created_at: Generated<Timestamp | null>;
  es_agregado_vuelo: Generated<boolean>;
  es_comprado: Generated<boolean>;
  id: Generated<string>;
  is_catalog: Generated<boolean>;
  marca: string | null;
  precio_total: Numeric | null;
  precio_unitario: Numeric | null;
  /**
   * FK a product_user_custom. Puede ser NULL si el producto fue eliminado.
   */
  product_custom_id: string | null;
  /**
   * DEPRECATED: No usar. Mantener solo para historial legacy.
   */
  product_id: string | null;
  razon_no_comprado: string | null;
  shopping_execution_id: string;
  shopping_list_item_id: string | null;
  unidad_medida: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface ShoppingExecutions {
  categoria_sobre_id: string | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  gasto_id: string | null;
  id: Generated<string>;
  /**
   * Category selected by list owner when registering a purchase made by invited user
   */
  owner_categoria_id: string | null;
  /**
   * Status of owner registration for purchases made by invited users. Values: null (not applicable), pending, registered, dismissed
   */
  owner_registration_status: Generated<string | null>;
  /**
   * Sobre selected by list owner when registering a purchase made by invited user
   */
  owner_sobre_id: string | null;
  /**
   * Subcategory/brand selected by list owner when registering a purchase made by invited user
   */
  owner_subcategoria_id: string | null;
  shopping_list_id: string;
  sobre_id: string | null;
  started_at: Generated<Timestamp | null>;
  status: Generated<string>;
  store_name: string | null;
  /**
   * Reference to the brand/store where the purchase was made (e.g., Jumbo, Costco)
   */
  subcategoria_id: string | null;
  tiempo_transcurrido: number | null;
  total_calculated: Numeric | null;
  total_estimado: Numeric | null;
  total_manual: Numeric | null;
  updated_at: Generated<Timestamp | null>;
  user_id: string;
}

export interface ShoppingListCollaborators {
  added_by: string;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  permission_level: string;
  shopping_list_id: string;
  user_id: string;
}

export interface ShoppingListItems {
  cantidad: Generated<Numeric>;
  categoria_global_id: string | null;
  categoria_producto_id: string | null;
  comentario: string | null;
  created_at: Generated<Timestamp | null>;
  created_by: string;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  /**
   * DEPRECATED: Siempre false. Usar product_custom_id.
   */
  is_catalog: Generated<boolean>;
  item_order: number;
  item_type: Generated<string>;
  marca: string | null;
  /**
   * SIEMPRE usar este campo. FK a product_user_custom.
   */
  product_custom_id: string | null;
  /**
   * DEPRECATED: No usar. Mantener solo para migración de datos legacy. Usar product_custom_id.
   */
  product_id: string | null;
  shopping_list_id: string;
  unidad_medida: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface ShoppingLists {
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  descripcion: string | null;
  id: Generated<string>;
  list_order: number | null;
  nombre: string;
  /**
   * Number of times this list has been used for shopping executions
   */
  purchase_count: Generated<number>;
  updated_at: Generated<Timestamp | null>;
  user_id: string;
}

export interface Sobres {
  ahorrado_actual: Numeric | null;
  color: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  emoji: string | null;
  gastado: Generated<Numeric | null>;
  id: Generated<string>;
  is_compartido: Generated<boolean>;
  max_participantes: Generated<number>;
  meta_objetivo: Numeric | null;
  moneda_principal_id: Generated<string>;
  nombre: string;
  presupuesto_asignado: Generated<Numeric | null>;
  presupuestos_multimoneda: Json | null;
  tipo: Generated<string>;
  updated_at: Generated<Timestamp>;
  usuario_id: string;
}

export interface SobresCategorias {
  categoria_id: string;
  created_at: Generated<Timestamp>;
  sobre_id: string;
}

export interface SobresCategoriasCuotas {
  categoria_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  /**
   * Target spending limit for this category (not enforced, only visual)
   */
  monto_cuota: Numeric;
  presupuesto_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SobresGastosResumen {
  /**
   * Count of transactions (maintained automatically)
   */
  cantidad_transacciones: Generated<number>;
  categoria_id: string | null;
  id: Generated<string>;
  periodo_month: number;
  periodo_year: number;
  sobre_id: string;
  /**
   * Sum of all expense transactions (maintained automatically)
   */
  total_gastado: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
}

export interface SobresPresupuestos {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  /**
   * Total budget amount for the envelope in this period
   */
  monto_global: Generated<Numeric | null>;
  periodo_month: number;
  periodo_year: number;
  /**
   * Enable/disable budget tracking (soft limits)
   */
  presupuesto_enabled: Generated<boolean>;
  sobre_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SobresUsuarios {
  created_at: Generated<Timestamp>;
  gastado: Generated<Numeric>;
  permisos: Json | null;
  presupuesto_asignado: Generated<Numeric>;
  rol: Generated<string>;
  sobre_id: string;
  usuario_id: string;
}

export interface Subcategorias {
  categoria_id: string;
  color: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  emoji: string | null;
  id: Generated<string>;
  imagen_url: string | null;
  nombre: string;
  updated_at: Generated<Timestamp>;
  usuario_id: string;
}

export interface SubcategoriasGlobales {
  categoria_tipo: string | null;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  emoji: string | null;
  id: Generated<string>;
  imagen_url: string | null;
  nombre: string;
  pais: string;
  updated_at: Generated<Timestamp | null>;
}

export interface SubscriptionHistory {
  created_at: Generated<Timestamp>;
  event_type: SubscriptionEventType;
  from_plan_id: string | null;
  id: Generated<string>;
  /**
   * Datos adicionales en formato JSON
   */
  metadata: Json | null;
  platform: SubscriptionPlatform | null;
  to_plan_id: string | null;
  user_id: string;
}

export interface SubscriptionPlans {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  /**
   * Máximo de usuarios que pueden vincularse a este plan
   */
  max_linked_users: Generated<number>;
  name: string;
  /**
   * Identificador único del plan (free, premium, familiar)
   */
  slug: string;
  /**
   * Días de trial gratuito al activar el plan (0 = sin trial)
   */
  trial_days: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface Themes {
  category: Generated<ThemeCategory>;
  colors: Json;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface TiposCambio {
  created_at: Generated<Timestamp>;
  fecha: Timestamp;
  fuente: string | null;
  moneda_destino: string;
  moneda_origen: string;
  tasa: Numeric;
}

export interface Transacciones {
  auto_aumento_sobre: Json | null;
  billetera_destino_id: string | null;
  billetera_id: string;
  categoria_id: string | null;
  conversion_info: Json | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  descripcion: string | null;
  fecha: Generated<Timestamp>;
  id: Generated<string>;
  moneda_id: string;
  monto: Numeric;
  /**
   * Source of the transaction: MANUAL (regular envelope transactions), SHOPPING_LIST (from shopping executions), INGRESO_RECURRENTE (recurring income), TRANSFERENCIA (transfers)
   */
  origen: Generated<string | null>;
  pago_tc: Json | null;
  sobre_id: string | null;
  subcategoria_id: string | null;
  tipo: string;
  updated_at: Generated<Timestamp>;
  usuario_id: string;
  version: Generated<number>;
}

export interface UserConfig {
  created_at: Generated<Timestamp>;
  dia_inicio_periodo: Generated<number>;
  locale: Generated<string>;
  moneda_principal_id: Generated<string>;
  monedas_habilitadas: Generated<string[]>;
  /**
   * Código de país ISO (CL, AR, PE, MX, ES, etc.)
   */
  pais: string | null;
  primer_dia_semana: Generated<number>;
  timezone: Generated<string>;
  tipo_periodo: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UserPreferences {
  created_at: Generated<Timestamp | null>;
  /**
   * Whether to group shopping list items by category
   */
  group_by_category: Generated<boolean>;
  id: Generated<string>;
  /**
   * Whether to use quick list mode (text-based entry)
   */
  quick_list_mode: Generated<boolean>;
  /**
   * Whether to show inline quantity editing in shopping lists
   */
  show_inline_qty: Generated<boolean>;
  updated_at: Generated<Timestamp | null>;
  user_id: string;
}

export interface Users {
  /**
   * Tipo de cuenta primaria (EMAIL o PHONE)
   */
  account_type: Generated<AccountType>;
  created_at: Generated<Timestamp>;
  email: string | null;
  /**
   * Fecha de verificación del email (NULL si no verificado)
   */
  email_verified: Timestamp | null;
  /**
   * ID único generado por PostgreSQL (TEXT para compatibilidad)
   */
  id: Generated<string>;
  image: string | null;
  last_login_at: Timestamp | null;
  name: string;
  password: string | null;
  phone: string | null;
  /**
   * Fecha de verificación del teléfono (NULL si no verificado)
   */
  phone_verified: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface UserSubscriptions {
  cancelled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: Generated<string>;
  period: SubscriptionPeriod | null;
  plan_id: string;
  platform: SubscriptionPlatform | null;
  /**
   * ID de la suscripción en Stripe/Apple/Google
   */
  platform_subscription_id: string | null;
  started_at: Generated<Timestamp>;
  status: Generated<SubscriptionStatus>;
  /**
   * Fecha de fin del trial (NULL si no está en trial)
   */
  trial_ends_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UserThemePreferences {
  created_at: Generated<Timestamp>;
  custom_colors: Json | null;
  id: Generated<string>;
  theme_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface VerificationCodes {
  /**
   * Código de verificación (6 dígitos)
   */
  code: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  /**
   * Estado del código
   */
  status: Generated<VerificationCodeStatus>;
  /**
   * Tipo de verificación
   */
  type: VerificationCodeType;
  updated_at: Generated<Timestamp>;
  used_at: Timestamp | null;
  user_id: string;
}

export interface VerificationTokens {
  expires: Timestamp;
  /**
   * Email o identificador del usuario
   */
  identifier: string;
  /**
   * Token único de verificación
   */
  token: string;
}

export interface DB {
  accounts: Accounts;
  asignaciones_presupuesto: AsignacionesPresupuesto;
  billeteras: Billeteras;
  billeteras_transacciones: BilleterasTransacciones;
  categorias: Categorias;
  ingresos_recurrentes: IngresosRecurrentes;
  invalidated_sessions: InvalidatedSessions;
  invitaciones_listas: InvitacionesListas;
  invitaciones_sobres: InvitacionesSobres;
  invitation_codes: InvitationCodes;
  linked_users: LinkedUsers;
  monedas: Monedas;
  notificaciones: Notificaciones;
  payment_products: PaymentProducts;
  pending_purchases: PendingPurchases;
  periodos: Periodos;
  plan_capabilities: PlanCapabilities;
  plan_limits: PlanLimits;
  presupuesto_ajustes_log: PresupuestoAjustesLog;
  product_catalog: ProductCatalog;
  product_categories_global: ProductCategoriesGlobal;
  product_categories_user: ProductCategoriesUser;
  product_favorites: ProductFavorites;
  product_frequency: ProductFrequency;
  product_prices_history: ProductPricesHistory;
  product_user_custom: ProductUserCustom;
  sessions: Sessions;
  shopping_execution_items: ShoppingExecutionItems;
  shopping_executions: ShoppingExecutions;
  shopping_list_collaborators: ShoppingListCollaborators;
  shopping_list_items: ShoppingListItems;
  shopping_lists: ShoppingLists;
  sobres: Sobres;
  sobres_categorias: SobresCategorias;
  sobres_categorias_cuotas: SobresCategoriasCuotas;
  sobres_gastos_resumen: SobresGastosResumen;
  sobres_presupuestos: SobresPresupuestos;
  sobres_usuarios: SobresUsuarios;
  subcategorias: Subcategorias;
  subcategorias_globales: SubcategoriasGlobales;
  subscription_history: SubscriptionHistory;
  subscription_plans: SubscriptionPlans;
  themes: Themes;
  tipos_cambio: TiposCambio;
  transacciones: Transacciones;
  user_config: UserConfig;
  user_preferences: UserPreferences;
  user_subscriptions: UserSubscriptions;
  user_theme_preferences: UserThemePreferences;
  users: Users;
  verification_codes: VerificationCodes;
  verification_tokens: VerificationTokens;
}
